export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL";
export const ADD_ADDRESS_RESET = "ADD_ADDRESS_RESET";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";
export const UPDATE_ADDRESS_RESET = "UPDATE_ADDRESS_RESET";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";
export const DELETE_ADDRESS_RESET = "DELETE_ADDRESS_RESET"

export const ALL_ADDRESS_REQUEST = "ALL_ADDRESS_REQUEST";
export const ALL_ADDRESS_SUCCESS = "ALL_ADDRESS_SUCCESS";
export const ALL_ADDRESS_FAIL = "ALL_ADDRESS_FAIL";

export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";