export const ALL_ATTRIBUTES_REQUEST = "ALL_ATTRIBUTES_REQUEST";
export const ALL_ATTRIBUTES_SUCCESS = "ALL_ATTRIBUTES_SUCCESS";
export const ALL_ATTRIBUTES_FAIL    = "ALL_ATTRIBUTES_FAIL";

export const ATTRIBUTE_DETAILS_REQUEST = "ATTRIBUTE_DETAILS_REQUEST";
export const ATTRIBUTE_DETAILS_SUCCESS = "ATTRIBUTE_DETAILS_SUCCESS";
export const ATTRIBUTE_DETAILS_FAIL    = "ATTRIBUTE_DETAILS_FAIL";

export const NEW_ATTRIBUTE_REQUEST = "NEW_ATTRIBUTE_REQUEST";
export const NEW_ATTRIBUTE_SUCCESS = "NEW_ATTRIBUTE_SUCCESS";
export const NEW_ATTRIBUTE_RESET   = "NEW_ATTRIBUTE_RESET";
export const NEW_ATTRIBUTE_FAIL    = "NEW_ATTRIBUTE_FAIL";

export const UPDATE_ATTRIBUTE_REQUEST = "UPDATE_ATTRIBUTE_REQUEST";
export const UPDATE_ATTRIBUTE_SUCCESS = "UPDATE_ATTRIBUTE_SUCCESS";
export const UPDATE_ATTRIBUTE_RESET   = "UPDATE_ATTRIBUTE_RESET";
export const UPDATE_ATTRIBUTE_FAIL    = "UPDATE_ATTRIBUTE_FAIL";

export const DELETE_ATTRIBUTE_REQUEST = "DELETE_ATTRIBUTE_REQUEST";
export const DELETE_ATTRIBUTE_SUCCESS = "DELETE_ATTRIBUTE_SUCCESS";
export const DELETE_ATTRIBUTE_RESET   = "DELETE_ATTRIBUTE_RESET";
export const DELETE_ATTRIBUTE_FAIL    = "DELETE_ATTRIBUTE_FAIL";

export const CLEAR_ERRORS        = "CLEAR_ERRORS";