export const ALL_ATTRIBUTESET_REQUEST = "ALL_ATTRIBUTESET_REQUEST";
export const ALL_ATTRIBUTESET_SUCCESS = "ALL_ATTRIBUTESET_SUCCESS";
export const ALL_ATTRIBUTESET_FAIL    = "ALL_ATTRIBUTESET_FAIL";

export const ATTRIBUTESET_DETAILS_REQUEST = "ATTRIBUTESET_DETAILS_REQUEST";
export const ATTRIBUTESET_DETAILS_SUCCESS = "ATTRIBUTESET_DETAILS_SUCCESS";
export const ATTRIBUTESET_DETAILS_FAIL    = "ATTRIBUTESET_DETAILS_FAIL";

export const NEW_ATTRIBUTESET_REQUEST = "NEW_ATTRIBUTESET_REQUEST";
export const NEW_ATTRIBUTESET_SUCCESS = "NEW_ATTRIBUTESET_SUCCESS";
export const NEW_ATTRIBUTESET_RESET   = "NEW_ATTRIBUTESET_RESET";
export const NEW_ATTRIBUTESET_FAIL    = "NEW_ATTRIBUTESET_FAIL";

export const UPDATE_ATTRIBUTESET_REQUEST = "UPDATE_ATTRIBUTESET_REQUEST";
export const UPDATE_ATTRIBUTESET_SUCCESS = "UPDATE_ATTRIBUTESET_SUCCESS";
export const UPDATE_ATTRIBUTESET_RESET   = "UPDATE_ATTRIBUTESET_RESET";
export const UPDATE_ATTRIBUTESET_FAIL    = "UPDATE_ATTRIBUTESET_FAIL";

export const DELETE_ATTRIBUTESET_REQUEST = "DELETE_ATTRIBUTESET_REQUEST";
export const DELETE_ATTRIBUTESET_SUCCESS = "DELETE_ATTRIBUTESET_SUCCESS";
export const DELETE_ATTRIBUTESET_RESET   = "DELETE_ATTRIBUTESET_RESET";
export const DELETE_ATTRIBUTESET_FAIL    = "DELETE_ATTRIBUTESET_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
