export const ADD_BANNER_REQUEST = "ADD_BANNER_REQUEST";
export const ADD_BANNER_SUCCESS = "ADD_BANNER_SUCCESS";
export const ADD_BANNER_FAIL = "ADD_BANNER_FAIL";
export const ADD_BANNER_RESET = "ADD_BANNER_RESET";

export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAIL = "UPDATE_BANNER_FAIL";
export const UPDATE_BANNER_RESET = "UPDATE_BANNER_RESET";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";
export const DELETE_BANNER_RESET = "DELETE_BANNER_RESET"

export const ALL_BANNER_REQUEST = "ALL_BANNER_REQUEST";
export const ALL_BANNER_SUCCESS = "ALL_BANNER_SUCCESS";
export const ALL_BANNER_FAIL = "ALL_BANNER_FAIL";

export const GET_BANNER_REQUEST = "GET_BANNER_REQUEST";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAIL = "GET_BANNER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";