export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL    = "CREATE_BLOG_FAIL";
export const CREATE_BLOG_RESET   = "CREATE_BLOG_FAIL";

export const LIST_BLOG_REQUEST = "LIST_BLOG_REQUEST";
export const LIST_BLOG_SUCCESS = "LIST_BLOG_SUCCESS";
export const LIST_BLOG_FAIL    = "LIST_BLOG_FAIL";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL    = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_RESET   = "DELETE_BLOG_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";