export const CREATE_BLOG_CATEGORY_REQUEST = "CREATE_BLOG_CATEGORY_REQUEST";
export const CREATE_BLOG_CATEGORY_SUCCESS = "CREATE_BLOG_CATEGORY_SUCCESS";
export const CREATE_BLOG_CATEGORY_FAIL    = "CREATE_BLOG_CATEGORY_FAIL";
export const CREATE_BLOG_CATEGORY_RESET    = "CREATE_BLOG_CATEGORY_RESET";

export const UPDATE_BLOG_CATEGORY_REQUEST = "UPDATE_BLOG_CATEGORY_REQUEST";
export const UPDATE_BLOG_CATEGORY_SUCCESS = "UPDATE_BLOG_CATEGORY_SUCCESS";
export const UPDATE_BLOG_CATEGORY_FAIL    = "UPDATE_BLOG_CATEGORY_FAIL";
export const UPDATE_BLOG_CATEGORY_RESET    = "UPDATE_BLOG_CATEGORY_RESET";

export const DETAIL_BLOG_CATEGORY_REQUEST = "DETAIL_BLOG_CATEGORY_REQUEST";
export const DETAIL_BLOG_CATEGORY_SUCCESS = "DETAIL_BLOG_CATEGORY_SUCCESS";
export const DETAIL_BLOG_CATEGORY_FAIL    = "DETAIL_BLOG_CATEGORY_FAIL";

export const ALL_BLOG_CATEGORY_REQUEST = "ALL_BLOG_CATEGORY_REQUEST";
export const ALL_BLOG_CATEGORY_SUCCESS = "ALL_BLOG_CATEGORY_SUCCESS";
export const ALL_BLOG_CATEGORY_FAIL = "ALL_BLOG_CATEGORY_FAIL";

export const DELETE_BLOG_CATEGORY_REQUEST = "DELETE_BLOG_CATEGORY_REQUEST";
export const DELETE_BLOG_CATEGORY_SUCCESS = "DELETE_BLOG_CATEGORY_SUCCESS";
export const DELETE_BLOG_CATEGORY_FAIL    = "DELETE_BLOG_CATEGORY_FAIL";
export const DELETE_BLOG_CATEGORY_RESET    = "DELETE_BLOG_CATEGORY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
