export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const REMOVE_CART_ITEM_AFTER_ORDER_PLACE = "REMOVE_CART_ITEM_AFTER_ORDER_PLACE";

export const VALIDATE_ADDRESS_REQUEST = "VALIDATE_ADDRESS_REQUEST";
export const VALIDATE_ADDRESS_SUCCESS = "VALIDATE_ADDRESS_SUCCESS";
export const VALIDATE_ADDRESS_FAIL = "VALIDATE_ADDRESS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
