export const CREATE_SETTING_REQUEST = "CREATE_SETTING_REQUEST";
export const CREATE_SETTING_SUCCESS = "CREATE_SETTING_SUCCESS";
export const CREATE_SETTING_FAIL    = "CREATE_SETTING_FAIL";
export const CREATE_SETTING_RESET   = "CREATE_SETTING_RESET";

export const GET_SETTING_REQUEST = "GET_SETTING_REQUEST";
export const GET_SETTING_SUCCESS = "GET_SETTING_SUCCESS";
export const GET_SETTING_FAIL    = "GET_SETTING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
