export const ADD_SLIDER_REQUEST = "ADD_SLIDER_REQUEST";
export const ADD_SLIDER_SUCCESS = "ADD_SLIDER_SUCCESS";
export const ADD_SLIDER_FAIL = "ADD_SLIDER_FAIL";
export const ADD_SLIDER_RESET = "ADD_SLIDER_RESET";

export const UPDATE_SLIDER_REQUEST = "UPDATE_SLIDER_REQUEST";
export const UPDATE_SLIDER_SUCCESS = "UPDATE_SLIDER_SUCCESS";
export const UPDATE_SLIDER_FAIL = "UPDATE_SLIDER_FAIL";
export const UPDATE_SLIDER_RESET = "UPDATE_SLIDER_RESET";

export const DELETE_SLIDER_REQUEST = "DELETE_SLIDER_REQUEST";
export const DELETE_SLIDER_SUCCESS = "DELETE_SLIDER_SUCCESS";
export const DELETE_SLIDER_FAIL = "DELETE_SLIDER_FAIL";
export const DELETE_SLIDER_RESET = "DELETE_SLIDER_RESET"

export const ALL_SLIDER_REQUEST = "ALL_SLIDER_REQUEST";
export const ALL_SLIDER_SUCCESS = "ALL_SLIDER_SUCCESS";
export const ALL_SLIDER_FAIL = "ALL_SLIDER_FAIL";

export const GET_SLIDER_REQUEST = "GET_SLIDER_REQUEST";
export const GET_SLIDER_SUCCESS = "GET_SLIDER_SUCCESS";
export const GET_SLIDER_FAIL = "GET_SLIDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";